@MySpot.Api_HostAddress = http://localhost:5000

### User Controller
###
POST {{MySpot.Api_HostAddress}}/users
Content-Type: application/json

{
  "email": "test@mail.com",
  "username": "user123",
  "password": "secret",
  "fullName": "User User",
  "role": "user"
}

###
GET {{MySpot.Api_HostAddress}}/users

### 
GET {{MySpot.Api_HostAddress}}/users/ebe7a009-69b7-4b27-9548-cedbaaabcbe6

### Parking Spots Controller
###
GET {{MySpot.Api_HostAddress}}/parking-spots

###
POST {{MySpot.Api_HostAddress}}/parking-spots/00000000-0000-0000-0000-000000000001/reservations/vehicle
Content-Type: application/json

{
  "parkingSpotId": "00000000-0000-0000-0000-000000000001",
  "capacity": 1,
  "employeeName": "Mark Milligan",
  "licensePlate": "ABC7734",
  "date": "2024-12-27"
}

###
POST {{MySpot.Api_HostAddress}}/parking-spots/reservations/cleaning
Content-Type: application/json

{
  "date": "2024-12-28"
}

###
GET {{MySpot.Api_HostAddress}}/Reservations/1f73729b-9a2d-400f-a1db-3bf0c03f2aa8

###
PUT {{MySpot.Api_HostAddress}}/Reservations/fbb3aeba-bbbd-497e-a0ed-6c5eac773090
Content-Type: application/json

{
  "licensePlate": "XYZ1234"
}

###
DELETE {{MySpot.Api_HostAddress}}/Reservations/9321b566-7dfd-46a6-9a94-fdaec822a74b
