@MySpot.Api_HostAddress = http://localhost:5000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMzE2NGEzNC04ZWJkLTQ3OGItODM5ZS05NWNhNmZjNTM4MzIiLCJ1bmlxdWVfbmFtZSI6IjIzMTY0YTM0LThlYmQtNDc4Yi04MzllLTk1Y2E2ZmM1MzgzMiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6ImFkbWluIiwibmJmIjoxNzM1NDc0ODQ1LCJleHAiOjE3MzU0Nzg0NDUsImlzcyI6Im15c3BvdC1pc3N1ZXIiLCJhdWQiOiJteXNwb3QtYXVkaWVuY2UifQ.d44XRIC950HPMTShk1toi5DjbRCFBMr-SVIftT635wM
### User Controller
###
POST {{MySpot.Api_HostAddress}}/users
Content-Type: application/json

{
  "email": "test-admin@mail.com",
  "username": "admin123",
  "password": "secret",
  "fullName": "Admin Admin",
  "role": "admin"
}

###
# @name sign-in
POST {{MySpot.Api_HostAddress}}/users/sign-in
Content-Type: application/json

{
  "email": "test-admin@mail.com",
  "password": "secret"
}

###
GET {{MySpot.Api_HostAddress}}/users/me
Authorization: Bearer {{accessToken}}

###
GET {{MySpot.Api_HostAddress}}/users/jwt

###
GET {{MySpot.Api_HostAddress}}/users
Authorization: Bearer {{accessToken}}

### 
GET {{MySpot.Api_HostAddress}}/users/ebe7a009-69b7-4b27-9548-cedbaaabcbe6

### Parking Spots Controller
###
GET {{MySpot.Api_HostAddress}}/parking-spots

###
POST {{MySpot.Api_HostAddress}}/parking-spots/00000000-0000-0000-0000-000000000001/reservations/vehicle
Content-Type: application/json

{
  "parkingSpotId": "00000000-0000-0000-0000-000000000001",
  "capacity": 1,
  "employeeName": "Mark Milligan",
  "licensePlate": "ABC7734",
  "date": "2024-12-27"
}

###
POST {{MySpot.Api_HostAddress}}/parking-spots/reservations/cleaning
Content-Type: application/json

{
  "date": "2024-12-28"
}

###
GET {{MySpot.Api_HostAddress}}/Reservations/1f73729b-9a2d-400f-a1db-3bf0c03f2aa8

###
PUT {{MySpot.Api_HostAddress}}/Reservations/fbb3aeba-bbbd-497e-a0ed-6c5eac773090
Content-Type: application/json

{
  "licensePlate": "XYZ1234"
}

###
DELETE {{MySpot.Api_HostAddress}}/Reservations/9321b566-7dfd-46a6-9a94-fdaec822a74b
